AWSTemplateFormatVersion: '2010-09-09'

#-------------------------------------------------
#Adding Parameters for the resources
#1 - Environment Size
#2 - VPC CIDR
#-------------------------------------------------
Parameters:
  EnvironmentSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select Environment Size (S,M,L)

  Vpccidr:
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/16
    Default: 10.20.0.0/16

  SubnetACidr:
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/16
    Default: 10.20.4.0/22

  SubnetBCidr:
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/16
    Default: 10.20.4.0/22

#-------------------------------------------------
#Adding Mapping for the resources
#1 - Region + instance AMI
#2 - Instance Size
#-------------------------------------------------
Mappings:
  RegionMap:
    us-east-1:
      AMALINUX: ami-0080e4c5bc078760e
    us-east-2:
      AMALINUX: ami-0cd3dfa4e37921605
    us-west-1:
      AMALINUX: ami-0ec6517f6edbf8044
    us-west-2:
      AMALINUX: ami-01e24be29428c15b2
    sa-east-1:
      AMALINUX: ami-05145e0b28ad8e0b2
    ca-central-1:
      AMALINUX: ami-07423fb63ea0a0930

  InstanceSize:
    SMALL:
      "EC2" : "t2.micro"
    MEDIUM:
      "EC2" : "t2.small"
    LARGE:
      "EC2" : "t2.medium"


#-------------------------------------------------
#Provisioning base VPC
#-------------------------------------------------
Resources:
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref Vpccidr

#-------------------------------------------------
#Adding two Subnets to the VPC
#-------------------------------------------------
  SubnetPublicSharedA:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: us-east-1a
      CidrBlock: !Ref SubnetACidr
      VpcId: !Ref VPC

  SubnetPublicSharedB:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: us-east-1a
      CidrBlock: !Ref SubnetBCidr
      VpcId: !Ref VPC

#-------------------------------------------------
#Adding one EC2 instance into Subnet B
#-------------------------------------------------
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !Ref SubnetPublicSharedB #!!its not automated yet...
      ImageId: !FindInMap [RegionMap, !Ref AWS::Region, AMALINUX] 
      InstanceType: !FindInMap [InstanceSize, !Ref EnvironmentSize, EC2] 